# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyBooks' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyBooks
pod 'Firebase','~> 4.9'
pod 'Firebase/Database'
end
